version: '3.8'
services:
  solr:
    image: solr:9.8
    container_name: solr
    ports:
     - "8983:8983"
    environment:
      - ZK_HOST=zoo:2181
    networks:
      - solr
    depends_on:
      - zoo
    volumes:
      - ./solr_task_updated:/var/solr
  zoo:
    image: zookeeper:3.8
    container_name: zoo
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_4LW_COMMANDS_WHITELIST: "mntr, conf, ruok"
    networks:
      - solr
  

networks:
  solr:
    driver: bridge
